dist: xenial
group: travis_latest

branches:
  only:
  - master

language: python

matrix:
  include:
  - python: "3.11"
    env: TOXENV=linters
  - python: "3.11"
    env: TOXENV=py311
  - python: "3.10"
    env: TOXENV=py310
  - python: "3.9"
    env: TOXENV=py39
  - python: "3.8"
    env: TOXENV=py38
  - python: "3.7"
    env: TOXENV=py37

install:
  - pip install --upgrade tox

script:
  - tox
